INSERT INTO mapels (id, kode, 
ama) VALUES
(1, 'R', 'RPL'),
(2, 'B', 'BHS INGGRIS'),
(3, 'C', 'CINEMATOGRAPHY'),
(4, 'D', 'DESIGN'),
(5, 'E', 'EKONOMI'),
(6, 'F', 'FISIKA'),
(7, 'G', 'GEOGRAFI'),
(8, 'H', 'HISTORY'),
(9, 'I', 'IPA'),
(10, 'J', 'JASMANI'),
(11, 'K', 'KIMIA'),
(12, 'L', 'LITERASI'),
(13, 'M', 'MATEMATIKA'),
(14, 'N', 'BAHASA INDONESIA'),
(15, 'O', 'ORGANISASI'),
(16, 'P', 'PKN'),
(17, 'Q', 'QURAN'),
(18, 'S', 'SENI BUDAYA'),
(19, 'T', 'TAJWID'),
(20, 'U', 'UMUM'),
(21, 'V', 'BHS JAWA'),
(22, 'W', 'PRAKARYA'),
(23, 'X', 'PJOK'),
(24, 'Y', 'BK'),
(25, 'Z', 'MULOK');